/*
 * Provider
 * The Provider API endpoints are intended to be implemented by mobility providers and consumed by regulatory agencies.  Data is **pulled** from providers by agencies. When a municipality queries information from a mobility provider, the Provider API has a historical view of operations in a standard format.  This specification contains a data standard for _mobility as a service_ providers to define a RESTful API for municipalities to access on-demand.  <img src=\"https://i.imgur.com/yzXrKpo.png\" width=\"120\" align=\"right\" alt=\"MDS Provider Icon\" border=\"0\">
 *
 * The version of the OpenAPI document: 2.0
 * Contact: info@openmobilityfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.muenchen.mobidam.client;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;
import java.util.Objects;
import lombok.Data;

@Data
/**
 * PostToken200Response
 */
@JsonPropertyOrder({
  PostToken200Response.JSON_PROPERTY_ACCESS_TOKEN,
  PostToken200Response.JSON_PROPERTY_EXPIRES_IN,
  PostToken200Response.JSON_PROPERTY_TOKEN_TYPE,
 })
@JsonTypeName("post_token_200_response")
public class PostToken200Response {
  public static final String JSON_PROPERTY_ACCESS_TOKEN = "access_token";
  @jakarta.annotation.Nonnull
  private String accessToken;

  public static final String JSON_PROPERTY_EXPIRES_IN = "expires_in";
  @jakarta.annotation.Nonnull
  private Long expiresIn;

  public static final String JSON_PROPERTY_TOKEN_TYPE = "token_type";
  @jakarta.annotation.Nonnull
  private String tokenType;

  private Instant issuedAt = Instant.now();

    public PostToken200Response() {
  }

  public PostToken200Response version(@jakarta.annotation.Nonnull String version) {
    
    this.accessToken = version;
    return this;
  }

  public boolean isValid() {
    Instant expirationTime = issuedAt.plusSeconds(getExpiresIn() - 15);
    return Instant.now().isBefore(expirationTime);
  }

  /**
   * The version of MDS this data represents.
   * @return version
   */
  @jakarta.annotation.Nonnull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The access token.")
  @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccessToken() {
    return accessToken;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessToken(@jakarta.annotation.Nonnull String accessToken) {
    this.accessToken = accessToken;
  }

  public PostToken200Response lastUpdated(@jakarta.annotation.Nonnull Long lastUpdated) {
    
    this.expiresIn = lastUpdated;
    return this;
  }

  /**
   * Timestamp indicating the last time the data in this feed was updated.
   * minimum: 1514764800000
   * @return lastUpdated
   */
  @jakarta.annotation.Nonnull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Timestamp indicating end of life.")
  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getExpiresIn() {
    return expiresIn;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresIn(@jakarta.annotation.Nonnull Long expiresIn) {
    this.expiresIn = expiresIn;
  }

  public PostToken200Response ttl(@jakarta.annotation.Nonnull String tokenType) {
    
    this.tokenType = tokenType;
    return this;
  }

  /**
   * Integer representing the number of milliseconds before the data in this feed will be updated again (0 if the data should always be refreshed). The data returned by a near-realtime endpoint should be as close to realtime as possible, but in no case should it be more than 5 minutes out-of-date.
   * minimum: 0
   * maximum: 300000
   * @return ttl
   */
  @jakarta.annotation.Nonnull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Integer representing the number of milliseconds before the data in this feed will be updated again (0 if the data should always be refreshed). The data returned by a near-realtime endpoint should be as close to realtime as possible, but in no case should it be more than 5 minutes out-of-date.")
  @JsonProperty(JSON_PROPERTY_TOKEN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTokenType() {
    return tokenType;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokenType(@jakarta.annotation.Nonnull String tokenType) {
    this.tokenType = tokenType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostToken200Response getVehiclesDeviceId200Response = (PostToken200Response) o;
    return Objects.equals(this.accessToken, getVehiclesDeviceId200Response.accessToken) &&
        Objects.equals(this.expiresIn, getVehiclesDeviceId200Response.expiresIn) &&
        Objects.equals(this.tokenType, getVehiclesDeviceId200Response.tokenType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, expiresIn, tokenType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostToken200Response {\n");
    sb.append("    access_token: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    expires_in: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    token_type: ").append(toIndentedString(tokenType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

